config/routes.rb
Rails.application.routes.draw do
    #get '/student/:user_id' => 'projects#display_public_view'
    get '/student/:user_id' => 'projects#index'
    
  devise_for :users
  #root "projects#index"
  authenticated do
    root "projects#index", as: :root_path
    resources :projects
  end

  unauthenticated do
    root to: "home#index"
    resources :projects
  end
end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
=begin
Active Record Validation
    Purpose: Ensures that listed attributes
    will be a part of the Project class by marking it
    as invalid when given erroneous test data by RSpec.
=end

class Project < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :projects
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# This is a basic HomeController with an index that does one thing: render 
# the view file associated with the controller action

class HomeController < ApplicationController
    def index
        render
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  # GET /projects or /projects.json
  def index
    @user_signed_in = user_signed_in?
    if user_signed_in?
      @projects = current_user.projects.all
    else
      set_user
      if params.has_key?(:user_id)
        @user_id = params[:user_id]
      end
      @projects = @user.projects.all
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @user_signed_in = user_signed_in?
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/general/_boot-header.html.erb
<style>
body {
    padding-top: 60px;
}
</style>
<link
href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
rel="stylesheet">
<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js">
</script>
<script src="https://kit.fontawesome.com/52ddef816e.js" crossorigin="anonymous"></script>

app/views/general/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "Home", root_path, class: "nav-link #{'active font-weight-bold'}" %>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#"
                    role="button"
                    data-bs-toggle="dropdown">Account</a>
                <ul class="dropdown-menu">
                <% if user_signed_in? %>
                    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm text-dark"  %>
                    <%= link_to "New Project", new_project_path, class: "nav-link text-dark #{'active font-weight-bold' if current_page?(new_user_session_path)}" %>
                <% else %>
                    <%= link_to "Log in", new_user_session_path, class: "nav-link text-dark #{'active font-weight-bold text-dark' if current_page?(new_user_session_path)}" %>
                    <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-dark #{'active font-weight-bold text-dark' if current_page?(new_user_registration_path)}" %>
                <% end %>
                </ul>
            </li>
        </ul>
    </div>
</nav>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <%= render "general/boot-header" %>
    <title>CS3300 Portfolio Project</title>
  </head>
    <body class="bg-dark text-white">
      <div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin">
        <div class="modal-dialog" role="document">
        <div class="modal-content rounded-1 bg-secondary">
        <div class="modal-header p-5 pb-4 border-bottom-0 d-block text-center">
          <h4>CS 3300 Portfolio Project - Fall 2022</h4>
        </div>
        <div class="modal-body pt-0 text-center">
          <div style="padding-left: 2rem;">
          <h5 class="pb-5"> Student: Derek Gary </h5>
        </div>
        <div class="modal-footer d-flex justify-content-center ">
        <% if user_signed_in? %>
          <div> Welcome <%= current_user.email %> </div>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %> 
        
        <% else %>
          <a href="users/sign_in" class="btn btn-lg btn-success btn-block"> Sign in</a>
        <% end %>
      </div>
        </div>
        </div>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300project2022</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
  <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<body class='bg-dark'>
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-1 bg-secondary">
        <div class="modal-header p-5 pb-4 border-bottom-0">
          <% if project.persisted? %>
            <h1 class="fw-normal mb-2 fs-2 text-light">Edit Project</h1>
          <% else %>
            <h1 class="fw-normal mb-2 fs-2 text-light">Create Project</h1>
          <% end %>
        </div>
        <div class="modal-body p-5 pt-0">
          <div class="input-group mb-3">
            <span class="input-group-text" id="basic-project-title">Title</span>
            <%= form.text_field :title, class: "form-control", id: "title"%>
          </div>
          <div class="form-floating">
            <%= form.text_area :description, class: "form-control mb-1", id: "description" %>
            <label for="floatingTextarea">Description</label>
          </div>
          <div class="d-grid gap-2 pt-4">
            <%= form.submit project.persisted? ? 'Update Project' : 'Create Project', class:"btn btn-success btn-large" %>
          </div>
        </div>
        <div class="modal-footer ps-5 d-grid d-md-block mt-3">
          <%= link_to "Back to projects", projects_path, class: "btn btn-dark"%>
          <% if project.persisted? %>
            <%= link_to "Show this project", @project, class: "btn btn-dark" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</body>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Title:</strong>
    <%= project.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<head>
  <%= render "general/boot-header" %>
</head>
<%= render "general/navbar" %>
<%= render "form", project: @project%>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Bootstrap 5 Website Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render "general/boot-header" %>
</head>

<body class="bg-dark">
    <%= render "general/navbar" %>

        <div class="container text-white">
            <h1 class="display-3">My Portfolio</h1>
            <p>Hi, my name is Derek Gary and this is my portfolio that I
                made for CS3300. My UCCS degree program is <a
                    href="https://www.uccs.edu/degreesandprograms/bacs">Bachelor
                    of Arts in Computer Science</a>.</p>
            <div class="text-dark">
                <ul class="list-group text">
                    <ul class="list-group-item">Programming Languages
                        <div class="mx-5">
                            <li>C++</li>
                            <li>C#</li>
                            <li>Java</li>
                            <li>Python</li>
                            <li>TypeScript</li>
                            <li>Ruby</li>
                        </div>
                    </ul>
                    <ul class="list-group-item">Technical Skills
                        <div class="mx-5">
                            <li>Testing</li>
                            <li>Debugging</li>
                            <li>Source Control</li>
                            <li>Technical Writing</li>
                        </div>
                    </ul>
                    <ul class="list-group-item">Soft Skills
                        <div class="mx-5">
                            <li>Problem-Solving Ability</li>
                            <li>Conflict Resolution</li>
                            <li>Adaptable</li>
                            <li>Motivated</li>
                        </div>
                    </ul>
                </ul>

                <% @projects.in_groups_of(3, false).each do |row_group| %>
                    <div class="d-flex flex-row pt-4 gap-3">
                        <% row_group.each do |individual_project| %>
                            <div class="col sm-3"  style="width:50%">
                                <div class="card card-body border-success d-flex flex-column" style="height:auto">
                                <h4 class="card-title"><%= individual_project.title %></h4>
                                <p class="card-text"><%= individual_project.description %></p>
                                <%= link_to "Show this project »", individual_project, class:"btn btn-primary mt-auto"%>
                                </div>
                            </div>
                        <% end %>
                    </div>
                <% end %>
            </div>
            <footer class="p-4 rounded">
                <hr class="hr" />
                <div class="copyright">
                    <p>Created using Ruby on Rails and Bootstrap</p>
                </div>
            </footer>
</body>

</html>

app/views/projects/new.html.erb
<html>
  <head>
    <%= render "general/boot-header" %>
  </head>
  <%= render "general/navbar"%>
  <%= render "form", project: @project %>
</html>

app/views/projects/show.html.erb
<head>
  <%= render "general/boot-header" %>
</head>
<%= render "general/navbar" %>

<p style="color: green"><%= notice %></p>

<body class="bg-dark text-light">
  <div class="modal position-static d-block py-5" tabindex="-1">
  <div class="modal-dialog">
      <div class="modal-content rounded-1 bg-secondary">
        <div class="modal-header p-4 pb-4">
          <h3 class="modal-title">Project View</h3>
        </div>
        <div class="modal-body p-5 pt-4">
          <%= render @project %>
        </div>
        <div class="modal-footer">
          <% if @user_signed_in %>
            <%= link_to "Back to projects", projects_path, class: "btn btn-dark" %>
            <%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-dark" %>
            <%= button_to "Destroy this project", @project, method: :delete, class: "btn btn-danger" %>
          <% else %>
              <%= link_to "Back to projects", :back, class: "btn btn-dark" %>
          <% end %>
        </div>
    </div>
  </div>
  <div>
  </div>
</body>

app/views/users/_form.html.erb
<head>
<%= render "general/boot-header" %>
</head>
<%= render "general/navbar"%>
<body class="bg-dark">
    <div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-1 bg-secondary">
        <div class="modal-header p-5 pb-4 border-bottom-0 d-block text-center">
            <h2 class="text-light"><%= title %></h2>
        </div>
        <div class="modal-body p-5 pt-0 text-center">
            <%= yield %>
        </div>
        <div class="modal-footer ps-5 d-grid d-md-block mt-3">
        <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
          <%= title %>
        <% end %>
        <%= render "users/shared/links" %>
        </div>
      </div>
    </div>
  </div>
  </body>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation", class="text-light">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-primary' %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'text-light' %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>